[package]
name = "DolaPortal"
version = "0.0.1"

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
# App
dola_portal = "_"
serde = "_"
dola_types = "_"
omnipool = "_"
# Wormhole
wormhole = "_"
deployer = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "cb4ba0a57c998c60cbab65af31a64875d2588ca5"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
rev = "9c2847d6e667851e9343227b5be4f0fa5c73ff6f"
subdir = "aptos/wormhole"

[dependencies.OmniPool]
local = "../omnipool"

[dependencies.Serde]
local = "../serde"

[dependencies.DolaTypes]
local = "../dola_types"
